---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ingest-exporter
  namespace: raspi-environment
  labels:
    role: ingestion
spec:
  replicas: 1
  strategy: 
    type: "RollingUpdate"
  template: 
    metadata:
      labels:
        app: ingest-exporter
    spec:
      dnsPolicy: Default
      containers:
         - name: ingest-exporter
           imagePullPolicy: Always
           image: quay.io/humancellatlas/ingest-exporter:develop_5
           env:
             - name: INGEST_API
               value: http://${INGEST_CORE_SERVICE_SERVICE_HOST}:${INGEST_CORE_SERVICE_SERVICE_PORT}
             - name: RABBIT_URL
               value: amqp://${RABBIT_SERVICE_SERVICE_HOST}:${RABBIT_SERVICE_SERVICE_PORT_SERVICE}
             - name: STAGING_API
               value: https://upload.data.humancellatlas.org
             - name: DSS_API
               value: https://dss.data.humancellatlas.org
             - name: BUNDLE_SCHEMA_BASE_URL
               value: https://raw.githubusercontent.com/HumanCellAtlas/metadata-schema/%s/json_schema/
             - name: SCHEMA_VERSION
               value: 4.6.1
             - name: INGEST_API_KEY
               valueFrom:
                 secretKeyRef:
                   name: api-keys
                   key: staging-api-key 
