---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ingest-accessioner
  namespace: raspi-environment
  labels:
    role: ingestion
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: ingest-accessioner
    spec:
      containers:
         - name: ingest-accessioner
           image: quay.io/humancellatlas/ingest-accessioner:stable_5
           env:
             - name: INGEST_API
               value: http://${INGEST_CORE_SERVICE_SERVICE_HOST}:${INGEST_CORE_SERVICE_SERVICE_PORT}
             - name: RABBIT_URL
               value: amqp://${RABBIT_SERVICE_SERVICE_HOST}:${RABBIT_SERVICE_SERVICE_PORT_SERVICE}
             - name: RABBITMQ_ACCESSION_QUEUE
               value: ingest.metadata.accession.queue
             - name: RABBITMQ_VALIDATION_QUEUE
               value: ingest.metadata.validation.queue
