---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ingest-state-tracking
  namespace: raspi-environment
  labels:
    role: ingestion
spec:
  replicas: 1
  strategy: 
    type: "RollingUpdate"
  template: 
    metadata:
      labels:
        app: ingest-state-tracking
    spec:
      containers:
         - name: ingest-state-tracking
           image: quay.io/humancellatlas/ingest-state-tracking:develop_5
           imagePullPolicy: Always
           env:
             - name: RABBIT_HOST
               value: ${RABBIT_SERVICE_SERVICE_HOST}
             - name: RABBIT_PORT
               value: ${RABBIT_SERVICE_SERVICE_PORT_SERVICE}
             - name: INGEST_API_ROOT
              value: http://${INGEST_CORE_SERVICE_SERVICE_HOST}:${INGEST_CORE_SERVICE_SERVICE_PORT}
             - name: UPDATER_PERIOD_SECONDS
               value: "1"
